apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    # Removed rewrite-target as it was causing a mismatch with the Flask app route
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # This tells the NGINX controller to manage this Ingress
  rules:
    # It's highly recommended to define a host for production.
    # For testing, if no other host-based ingresses exist, you might omit it,
    # but it's best practice to include it.
    # - host: your-backend-domain.com # <--- UNCOMMENT AND REPLACE WITH YOUR DOMAIN
    - http:
        paths:
          - path: /api/hello # Ingress path for /api/hello
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 80 # Service port
          - path: /messages # Ingress path for /messages (for both GET and POST)
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 80 # Service port
