apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80 # Service listens on port 80
      targetPort: 5000 # Routes to container's port 5000
  type: ClusterIP